export const DEFAULT_CARDS = [
  { id: 1, img: '/svg/angular.svg' },
  { id: 1, img: '/svg/angular.svg' },
  { id: 2, img: '/svg/aurelia.svg' },
  { id: 2, img: '/svg/aurelia.svg' },
  { id: 3, img: '/svg/backbone.svg' },
  { id: 3, img: '/svg/backbone.svg' },
  { id: 4, img: '/svg/ember.svg' },
  { id: 4, img: '/svg/ember.svg' },
  { id: 5, img: '/svg/js-badge.svg' },
  { id: 5, img: '/svg/js-badge.svg' },
  { id: 6, img: '/svg/react.svg' },
  { id: 6, img: '/svg/react.svg' },
  { id: 7, img: '/svg/vue.svg' },
  { id: 7, img: '/svg/vue.svg' },
  { id: 8, img: '/svg/node-js.svg' },
  { id: 8, img: '/svg/node-js.svg' },
]
